// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Web.Controllers
{
    public partial class AccountController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AccountController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Login()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ResetPassword()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPassword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ConfirmAccount()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfirmAccount);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ResendConfirmation()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResendConfirmation);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ShowMessage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowMessage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Listusers()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Listusers);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Register()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Register);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Edit()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DeleteUser()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteUser);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ResetUserPassword()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ResetUserPassword);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult GenerateConfirmationLink()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GenerateConfirmationLink);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SaveUserPassword()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveUserPassword);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AccountController Actions { get { return MVC.Account; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Account";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Account";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Login = "Login";
            public readonly string LogOff = "LogOff";
            public readonly string KeepAlive = "KeepAlive";
            public readonly string ForgotPassword = "ForgotPassword";
            public readonly string ResetPassword = "ResetPassword";
            public readonly string ConfirmAccount = "ConfirmAccount";
            public readonly string ResendConfirmation = "ResendConfirmation";
            public readonly string ShowMessage = "ShowMessage";
            public readonly string Manage = "Manage";
            public readonly string Listusers = "Listusers";
            public readonly string Register = "Register";
            public readonly string Edit = "Edit";
            public readonly string DeleteUser = "DeleteUser";
            public readonly string ResetUserPassword = "ResetUserPassword";
            public readonly string GenerateConfirmationLink = "GenerateConfirmationLink";
            public readonly string UserSettings = "UserSettings";
            public readonly string SaveUserPassword = "SaveUserPassword";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Login = "Login";
            public const string LogOff = "LogOff";
            public const string KeepAlive = "KeepAlive";
            public const string ForgotPassword = "ForgotPassword";
            public const string ResetPassword = "ResetPassword";
            public const string ConfirmAccount = "ConfirmAccount";
            public const string ResendConfirmation = "ResendConfirmation";
            public const string ShowMessage = "ShowMessage";
            public const string Manage = "Manage";
            public const string Listusers = "Listusers";
            public const string Register = "Register";
            public const string Edit = "Edit";
            public const string DeleteUser = "DeleteUser";
            public const string ResetUserPassword = "ResetUserPassword";
            public const string GenerateConfirmationLink = "GenerateConfirmationLink";
            public const string UserSettings = "UserSettings";
            public const string SaveUserPassword = "SaveUserPassword";
        }


        static readonly ActionParamsClass_Login s_params_Login = new ActionParamsClass_Login();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Login LoginParams { get { return s_params_Login; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Login
        {
            public readonly string returnUrl = "returnUrl";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ForgotPassword s_params_ForgotPassword = new ActionParamsClass_ForgotPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ForgotPassword ForgotPasswordParams { get { return s_params_ForgotPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ForgotPassword
        {
            public readonly string resetPasswordRequestModel = "resetPasswordRequestModel";
        }
        static readonly ActionParamsClass_ResetPassword s_params_ResetPassword = new ActionParamsClass_ResetPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetPassword ResetPasswordParams { get { return s_params_ResetPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetPassword
        {
            public readonly string resetPasswordToken = "resetPasswordToken";
            public readonly string userName = "userName";
            public readonly string resetPasswordModel = "resetPasswordModel";
        }
        static readonly ActionParamsClass_ConfirmAccount s_params_ConfirmAccount = new ActionParamsClass_ConfirmAccount();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ConfirmAccount ConfirmAccountParams { get { return s_params_ConfirmAccount; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ConfirmAccount
        {
            public readonly string userName = "userName";
            public readonly string confirmationToken = "confirmationToken";
            public readonly string confirmPasswordForTheAccount = "confirmPasswordForTheAccount";
        }
        static readonly ActionParamsClass_ResendConfirmation s_params_ResendConfirmation = new ActionParamsClass_ResendConfirmation();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResendConfirmation ResendConfirmationParams { get { return s_params_ResendConfirmation; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResendConfirmation
        {
            public readonly string email = "email";
        }
        static readonly ActionParamsClass_ShowMessage s_params_ShowMessage = new ActionParamsClass_ShowMessage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowMessage ShowMessageParams { get { return s_params_ShowMessage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowMessage
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Listusers s_params_Listusers = new ActionParamsClass_Listusers();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Listusers ListusersParams { get { return s_params_Listusers; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Listusers
        {
            public readonly string dataTablesParam = "dataTablesParam";
        }
        static readonly ActionParamsClass_Register s_params_Register = new ActionParamsClass_Register();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Register RegisterParams { get { return s_params_Register; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Register
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteUser s_params_DeleteUser = new ActionParamsClass_DeleteUser();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUser DeleteUserParams { get { return s_params_DeleteUser; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUser
        {
            public readonly string userName = "userName";
        }
        static readonly ActionParamsClass_ResetUserPassword s_params_ResetUserPassword = new ActionParamsClass_ResetUserPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ResetUserPassword ResetUserPasswordParams { get { return s_params_ResetUserPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ResetUserPassword
        {
            public readonly string userName = "userName";
        }
        static readonly ActionParamsClass_GenerateConfirmationLink s_params_GenerateConfirmationLink = new ActionParamsClass_GenerateConfirmationLink();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GenerateConfirmationLink GenerateConfirmationLinkParams { get { return s_params_GenerateConfirmationLink; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GenerateConfirmationLink
        {
            public readonly string userName = "userName";
        }
        static readonly ActionParamsClass_UserSettings s_params_UserSettings = new ActionParamsClass_UserSettings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UserSettings UserSettingsParams { get { return s_params_UserSettings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UserSettings
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SaveUserPassword s_params_SaveUserPassword = new ActionParamsClass_SaveUserPassword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SaveUserPassword SaveUserPasswordParams { get { return s_params_SaveUserPassword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SaveUserPassword
        {
            public readonly string currentPassword = "currentPassword";
            public readonly string newPassword = "newPassword";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ChangePasswordPartial = "_ChangePasswordPartial";
                public readonly string _ExternalLoginsListPartial = "_ExternalLoginsListPartial";
                public readonly string _RemoveExternalLoginsPartial = "_RemoveExternalLoginsPartial";
                public readonly string _SetPasswordPartial = "_SetPasswordPartial";
                public readonly string ConfirmAccount = "ConfirmAccount";
                public readonly string Edit = "Edit";
                public readonly string ExternalLoginConfirmation = "ExternalLoginConfirmation";
                public readonly string ExternalLoginFailure = "ExternalLoginFailure";
                public readonly string ForgotPassword = "ForgotPassword";
                public readonly string List = "List";
                public readonly string Login = "Login";
                public readonly string Manage = "Manage";
                public readonly string Register = "Register";
                public readonly string RegisterSuccess = "RegisterSuccess";
                public readonly string ResetPassword = "ResetPassword";
                public readonly string ShowMessage = "ShowMessage";
                public readonly string UserSettings = "UserSettings";
            }
            public readonly string _ChangePasswordPartial = "~/Views/Account/_ChangePasswordPartial.cshtml";
            public readonly string _ExternalLoginsListPartial = "~/Views/Account/_ExternalLoginsListPartial.cshtml";
            public readonly string _RemoveExternalLoginsPartial = "~/Views/Account/_RemoveExternalLoginsPartial.cshtml";
            public readonly string _SetPasswordPartial = "~/Views/Account/_SetPasswordPartial.cshtml";
            public readonly string ConfirmAccount = "~/Views/Account/ConfirmAccount.cshtml";
            public readonly string Edit = "~/Views/Account/Edit.cshtml";
            public readonly string ExternalLoginConfirmation = "~/Views/Account/ExternalLoginConfirmation.cshtml";
            public readonly string ExternalLoginFailure = "~/Views/Account/ExternalLoginFailure.cshtml";
            public readonly string ForgotPassword = "~/Views/Account/ForgotPassword.cshtml";
            public readonly string List = "~/Views/Account/List.cshtml";
            public readonly string Login = "~/Views/Account/Login.cshtml";
            public readonly string Manage = "~/Views/Account/Manage.cshtml";
            public readonly string Register = "~/Views/Account/Register.cshtml";
            public readonly string RegisterSuccess = "~/Views/Account/RegisterSuccess.cshtml";
            public readonly string ResetPassword = "~/Views/Account/ResetPassword.cshtml";
            public readonly string ShowMessage = "~/Views/Account/ShowMessage.cshtml";
            public readonly string UserSettings = "~/Views/Account/UserSettings.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AccountController : Web.Controllers.AccountController
    {
        public T4MVC_AccountController() : base(Dummy.Instance) { }

        [NonAction]
        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string returnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult Login(string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            LoginOverride(callInfo, returnUrl);
            return callInfo;
        }

        [NonAction]
        partial void LoginOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Web.Models.Account.LoginModel model, string returnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult Login(Web.Models.Account.LoginModel model, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Login);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            LoginOverride(callInfo, model, returnUrl);
            return callInfo;
        }

        [NonAction]
        partial void LogOffOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LogOff()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LogOff);
            LogOffOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void KeepAliveOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult KeepAlive()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.KeepAlive);
            KeepAliveOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ForgotPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ForgotPassword()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ForgotPassword);
            ForgotPasswordOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ForgotPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Web.Models.Account.ForgotPasswordModel resetPasswordRequestModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ForgotPassword(Web.Models.Account.ForgotPasswordModel resetPasswordRequestModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ForgotPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "resetPasswordRequestModel", resetPasswordRequestModel);
            ForgotPasswordOverride(callInfo, resetPasswordRequestModel);
            return callInfo;
        }

        [NonAction]
        partial void ResetPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string resetPasswordToken, string userName);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResetPassword(string resetPasswordToken, string userName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "resetPasswordToken", resetPasswordToken);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            ResetPasswordOverride(callInfo, resetPasswordToken, userName);
            return callInfo;
        }

        [NonAction]
        partial void ResetPasswordOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Web.Models.Account.ResetPasswordModel resetPasswordModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResetPassword(Web.Models.Account.ResetPasswordModel resetPasswordModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResetPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "resetPasswordModel", resetPasswordModel);
            ResetPasswordOverride(callInfo, resetPasswordModel);
            return callInfo;
        }

        [NonAction]
        partial void ConfirmAccountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string userName, string confirmationToken);

        [NonAction]
        public override System.Web.Mvc.ActionResult ConfirmAccount(string userName, string confirmationToken)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfirmAccount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "confirmationToken", confirmationToken);
            ConfirmAccountOverride(callInfo, userName, confirmationToken);
            return callInfo;
        }

        [NonAction]
        partial void ConfirmAccountOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Web.Models.Account.ConfirmPasswordForTheAccountModel confirmPasswordForTheAccount);

        [NonAction]
        public override System.Web.Mvc.ActionResult ConfirmAccount(Web.Models.Account.ConfirmPasswordForTheAccountModel confirmPasswordForTheAccount)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfirmAccount);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "confirmPasswordForTheAccount", confirmPasswordForTheAccount);
            ConfirmAccountOverride(callInfo, confirmPasswordForTheAccount);
            return callInfo;
        }

        [NonAction]
        partial void ResendConfirmationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string email);

        [NonAction]
        public override System.Web.Mvc.ActionResult ResendConfirmation(string email)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ResendConfirmation);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "email", email);
            ResendConfirmationOverride(callInfo, email);
            return callInfo;
        }

        [NonAction]
        partial void ShowMessageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Web.Models.Account.ShowMessageModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowMessage(Web.Models.Account.ShowMessageModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowMessage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ShowMessageOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ManageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Manage()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Manage);
            ManageOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ListusersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Mvc.JQuery.Datatables.DataTablesParam dataTablesParam);

        [NonAction]
        public override System.Web.Mvc.ActionResult Listusers(Mvc.JQuery.Datatables.DataTablesParam dataTablesParam)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Listusers);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "dataTablesParam", dataTablesParam);
            ListusersOverride(callInfo, dataTablesParam);
            return callInfo;
        }

        [NonAction]
        partial void RegisterOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Web.Models.Account.RegisterModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult Register(Web.Models.Account.RegisterModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Register);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            RegisterOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void EditOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Web.Models.Account.RegisterModel model);

        [NonAction]
        public override System.Web.Mvc.JsonResult Edit(Web.Models.Account.RegisterModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteUserOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string userName);

        [NonAction]
        public override System.Web.Mvc.JsonResult DeleteUser(string userName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DeleteUser);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            DeleteUserOverride(callInfo, userName);
            return callInfo;
        }

        [NonAction]
        partial void ResetUserPasswordOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string userName);

        [NonAction]
        public override System.Web.Mvc.JsonResult ResetUserPassword(string userName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ResetUserPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            ResetUserPasswordOverride(callInfo, userName);
            return callInfo;
        }

        [NonAction]
        partial void GenerateConfirmationLinkOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string userName);

        [NonAction]
        public override System.Web.Mvc.JsonResult GenerateConfirmationLink(string userName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GenerateConfirmationLink);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userName", userName);
            GenerateConfirmationLinkOverride(callInfo, userName);
            return callInfo;
        }

        [NonAction]
        partial void UserSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserSettings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserSettings);
            UserSettingsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UserSettingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Web.Models.Account.UserSettingsModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserSettings(Web.Models.Account.UserSettingsModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserSettings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            UserSettingsOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void SaveUserPasswordOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string currentPassword, string newPassword);

        [NonAction]
        public override System.Web.Mvc.JsonResult SaveUserPassword(string currentPassword, string newPassword)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SaveUserPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "currentPassword", currentPassword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "newPassword", newPassword);
            SaveUserPasswordOverride(callInfo, currentPassword, newPassword);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
