// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Web.Controllers
{
    public partial class TransactionController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TransactionController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult List()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult PostHl7OrderForm()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PostHl7OrderForm);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CheckandGetOrderJson()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckandGetOrderJson);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RejectionDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RejectionDetails);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TransactionController Actions { get { return MVC.Transaction; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Transaction";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Transaction";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string List = "List";
            public readonly string Welcome = "Welcome";
            public readonly string HL7EntryDetails = "HL7EntryDetails";
            public readonly string GetPayerList = "GetPayerList";
            public readonly string GetLabDataList = "GetLabDataList";
            public readonly string PostHl7OrderForm = "PostHl7OrderForm";
            public readonly string CheckandGetOrderJson = "CheckandGetOrderJson";
            public readonly string RejectionDetails = "RejectionDetails";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string List = "List";
            public const string Welcome = "Welcome";
            public const string HL7EntryDetails = "HL7EntryDetails";
            public const string GetPayerList = "GetPayerList";
            public const string GetLabDataList = "GetLabDataList";
            public const string PostHl7OrderForm = "PostHl7OrderForm";
            public const string CheckandGetOrderJson = "CheckandGetOrderJson";
            public const string RejectionDetails = "RejectionDetails";
        }


        static readonly ActionParamsClass_List s_params_List = new ActionParamsClass_List();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_List ListParams { get { return s_params_List; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_List
        {
            public readonly string postedDate = "postedDate";
            public readonly string CheckStatus = "CheckStatus";
        }
        static readonly ActionParamsClass_PostHl7OrderForm s_params_PostHl7OrderForm = new ActionParamsClass_PostHl7OrderForm();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PostHl7OrderForm PostHl7OrderFormParams { get { return s_params_PostHl7OrderForm; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PostHl7OrderForm
        {
            public readonly string orderFormData = "orderFormData";
        }
        static readonly ActionParamsClass_CheckandGetOrderJson s_params_CheckandGetOrderJson = new ActionParamsClass_CheckandGetOrderJson();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CheckandGetOrderJson CheckandGetOrderJsonParams { get { return s_params_CheckandGetOrderJson; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CheckandGetOrderJson
        {
            public readonly string hl7Jsonload = "hl7Jsonload";
        }
        static readonly ActionParamsClass_RejectionDetails s_params_RejectionDetails = new ActionParamsClass_RejectionDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RejectionDetails RejectionDetailsParams { get { return s_params_RejectionDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RejectionDetails
        {
            public readonly string postedDate = "postedDate";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string HL7EntryDetails = "HL7EntryDetails";
                public readonly string IndividualTransactionDisplay = "IndividualTransactionDisplay";
                public readonly string List = "List";
                public readonly string RejectionDetails = "RejectionDetails";
                public readonly string Report = "Report";
                public readonly string Welcome = "Welcome";
            }
            public readonly string HL7EntryDetails = "~/Views/Transaction/HL7EntryDetails.cshtml";
            public readonly string IndividualTransactionDisplay = "~/Views/Transaction/IndividualTransactionDisplay.cshtml";
            public readonly string List = "~/Views/Transaction/List.cshtml";
            public readonly string RejectionDetails = "~/Views/Transaction/RejectionDetails.cshtml";
            public readonly string Report = "~/Views/Transaction/Report.cshtml";
            public readonly string Welcome = "~/Views/Transaction/Welcome.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_TransactionController : Web.Controllers.TransactionController
    {
        public T4MVC_TransactionController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string postedDate, string CheckStatus);

        [NonAction]
        public override System.Web.Mvc.ActionResult List(string postedDate, string CheckStatus)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postedDate", postedDate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "CheckStatus", CheckStatus);
            ListOverride(callInfo, postedDate, CheckStatus);
            return callInfo;
        }

        [NonAction]
        partial void WelcomeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Welcome()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Welcome);
            WelcomeOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void HL7EntryDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult HL7EntryDetails()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HL7EntryDetails);
            HL7EntryDetailsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetPayerListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetPayerList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetPayerList);
            GetPayerListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetLabDataListOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetLabDataList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetLabDataList);
            GetLabDataListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PostHl7OrderFormOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Web.Models.HL7.HL7EntryFormViewModel orderFormData);

        [NonAction]
        public override System.Web.Mvc.JsonResult PostHl7OrderForm(Web.Models.HL7.HL7EntryFormViewModel orderFormData)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.PostHl7OrderForm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderFormData", orderFormData);
            PostHl7OrderFormOverride(callInfo, orderFormData);
            return callInfo;
        }

        [NonAction]
        partial void CheckandGetOrderJsonOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Web.Models.HL7.Hl7JsonloadViewModel hl7Jsonload);

        [NonAction]
        public override System.Web.Mvc.JsonResult CheckandGetOrderJson(Web.Models.HL7.Hl7JsonloadViewModel hl7Jsonload)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CheckandGetOrderJson);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "hl7Jsonload", hl7Jsonload);
            CheckandGetOrderJsonOverride(callInfo, hl7Jsonload);
            return callInfo;
        }

        [NonAction]
        partial void RejectionDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string postedDate);

        [NonAction]
        public override System.Web.Mvc.ActionResult RejectionDetails(string postedDate)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RejectionDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "postedDate", postedDate);
            RejectionDetailsOverride(callInfo, postedDate);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
